### Feed Forward Neural Network


In [13]:
import torch
from torch import autograd,nn,optim
import torch.nn.functional as F

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
torch.manual_seed(326)


In [14]:
# keep the hidden state high to add more non-linieraties
batch_size = 5
input_size = 3
hidden_size = 400
num_classes = 2
learning_rate = 0.005

In [15]:
input = autograd.Variable(torch.rand(batch_size,input_size)) 
print("input: \n",input)

input: 
 tensor([[0.9976, 0.2634, 0.4181],
        [0.2633, 0.6259, 0.1629],
        [0.2165, 0.4565, 0.9599],
        [0.9657, 0.8649, 0.2225],
        [0.9978, 0.8279, 0.4539]])


In [16]:
target = (torch.rand(batch_size) * num_classes).long()

print(target)

tensor([1, 1, 0, 1, 1])


In [17]:
class Model(nn.Module):
    
    def __init__(self,input_size,hidden_size,num_classes):
        
        super().__init__()
        
        self.h1 = nn.Linear(input_size,hidden_size)
        self.h2 = nn.Linear(hidden_size,num_classes)

    
    def forward(self,x):
        
        x = self.h1(x)
        x = torch.tanh(x)
        x = self.h2(x)
        x = F.softmax(x,dim=0)
        
        return(x)
        

In [18]:
model = Model(input_size = input_size,hidden_size = hidden_size,num_classes = num_classes)
out = model(input)
print('out \n',out)


out 
 tensor([[0.2036, 0.2286],
        [0.2003, 0.1795],
        [0.1932, 0.1838],
        [0.2033, 0.2027],
        [0.1996, 0.2055]], grad_fn=<SoftmaxBackward>)


### Since everything is random data, let's overfit to show the loss is going down

In [19]:
#Print the first target and prediction
print("target:",target)
_,pred = out.max(1)
print("prediction:",pred)

target: tensor([1, 1, 0, 1, 1])
prediction: tensor([1, 0, 0, 0, 1])


In [20]:
#Print the loss
loss = F.nll_loss(out,target)
print("loss:",loss.data)

loss: tensor(-0.2019)


In [21]:
model = Model(input_size = input_size,hidden_size = hidden_size,num_classes = num_classes)
opt = optim.Adam(params=model.parameters(),lr=learning_rate)


In [22]:
for epoch in range(50):    
    out = model(input)
    _,pred = out.max(1)
    print("target    :",target)
    print("prediction:",pred)

    loss = F.nll_loss(out,target)
    print("loss:",loss.data)

    model.zero_grad()
    loss.backward(retain_graph=True)
    opt.step()





target    : tensor([1, 1, 0, 1, 1])
prediction: tensor([0, 1, 1, 1, 0])
loss: tensor(-0.1982)
target    : tensor([1, 1, 0, 1, 1])
prediction: tensor([0, 1, 0, 1, 1])
loss: tensor(-0.2247)
target    : tensor([1, 1, 0, 1, 1])
prediction: tensor([1, 1, 0, 1, 1])
loss: tensor(-0.2516)
target    : tensor([1, 1, 0, 1, 1])
prediction: tensor([1, 0, 0, 1, 1])
loss: tensor(-0.2787)
target    : tensor([1, 1, 0, 1, 1])
prediction: tensor([1, 0, 0, 1, 1])
loss: tensor(-0.3051)
target    : tensor([1, 1, 0, 1, 1])
prediction: tensor([1, 1, 0, 1, 1])
loss: tensor(-0.3291)
target    : tensor([1, 1, 0, 1, 1])
prediction: tensor([1, 1, 0, 1, 1])
loss: tensor(-0.3493)
target    : tensor([1, 1, 0, 1, 1])
prediction: tensor([1, 1, 0, 1, 1])
loss: tensor(-0.3650)
target    : tensor([1, 1, 0, 1, 1])
prediction: tensor([1, 1, 0, 1, 1])
loss: tensor(-0.3763)
target    : tensor([1, 1, 0, 1, 1])
prediction: tensor([1, 1, 0, 1, 1])
loss: tensor(-0.3842)
target    : tensor([1, 1, 0, 1, 1])
prediction: tensor([1, 1